# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jamil Bou Kheir
tagline: Building and securing Internet systems since 2011.
email: blog@elbii.com
description: >- # this means to ignore newlines until "baseurl:"
  Full-stack Rails consultant interested in Blockchain, Machine Learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jamilbk.com"
author:
  name: Jamil Bou Kheir
  url: https://jamilbk.com
  gravatar: "https://gravatar.com/avatar/552dc0d1b9b17cd362fbc50eb22dad7c?s=200"
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

sidebar_home_link: true

# Specifying this auto-adds a download link which I don't want
# github:
#   repo: https://github.com/jamilbk/jamilbk.com.new
disqus:
  shortname: jamilbk


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
